### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by XXDRD** [polymorphicshade/NewPipe#106]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] This issue CANNOT be reproduced with the same version of upstream NewPipe 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

App crashes

### Expected behavior

To open the app

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/88576601/137637997-4ac96792-0748-42ce-93b7-7d6f1f5072d2.mp4

### Logs

    https://paste.crdroid.net/5MOSl8

time: 1634489026951
msg: java.lang.IllegalArgumentException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2569)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2631)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

stacktrace: java.lang.IllegalArgumentException: No such service ComponentInfo{org.polymorphicshade.newpipe/org.acra.sender.JobSenderService}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:308)
	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47)
	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.java:62)
	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.java:66)
	at org.acra.startup.StartupProcessorExecutor.lambda$null$0(StartupProcessorExecutor.java:86)
	at org.acra.startup.StartupProcessorExecutor.lambda$null$0$StartupProcessorExecutor(Unknown Source:0)
	at org.acra.startup.-$$Lambda$StartupProcessorExecutor$vr-B3Kby1WTBs7c-61N3dOEKizo.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2569)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2631)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

GitHub

### Device info

 - Android version/Custom ROM version:11
 - Device model:Redmi 4X (santoni)

**Comment by XXDRD** [comment]
Fixed with upstream merge

**Comment by Bortex19** [comment]
> Fixed with upstream merge

I have installed again the last version yesterday, it keeps failing

**Comment by Atemu** [comment]
We merge in the upstream changes whenever they release. This app is just regular NewPipe plus a few extras and the regular NewPipe part needs to stay up to date with upstream.

If this affects you, open a new issue. It clearly doesn't seem to affect @XXDRD anymore.

Have you tried exporting your data, clearing app storage and importing it again?

**Comment by Bortex19** [comment]
> We merge in the upstream changes whenever they release. This app is just regular NewPipe plus a few extras and the regular NewPipe part needs to stay up to date with upstream.
> 
> If this affects you, open a new issue. It clearly doesn't seem to affect @XXDRD anymore.
> 
> Have you tried exporting your data, clearing app storage and importing it again?

Thank you for your response.

I would like to export my data, but app crashes just after open it. I have clean cache and dalvik cache, but it didn't work.

**Comment by XXDRD** [comment]
> > We merge in the upstream changes whenever they release. This app is just regular NewPipe plus a few extras and the regular NewPipe part needs to stay up to date with upstream.
> > If this affects you, open a new issue. It clearly doesn't seem to affect @XXDRD anymore.
> > Have you tried exporting your data, clearing app storage and importing it again?
> 
> Thank you for your response.
> 
> I would like to export my data, but app crashes just after open it. I have clean cache and dalvik cache, but it didn't work.

Download the build which supports your device

**Comment by Bortex19** [comment]
> > > We merge in the upstream changes whenever they release. This app is just regular NewPipe plus a few extras and the regular NewPipe part needs to stay up to date with upstream.
> > > If this affects you, open a new issue. It clearly doesn't seem to affect @XXDRD anymore.
> > > Have you tried exporting your data, clearing app storage and importing it again?
> > 
> > 
> > Thank you for your response.
> > I would like to export my data, but app crashes just after open it. I have clean cache and dalvik cache, but it didn't work.
> 
> Download the build which supports your device Install from fdroid - automatically chooses app version according to your device info also to completely start fresh you need to clear data and not cache.

I have the version recommend by Fdroid, so the version is right. It was working until yesterday. I didn't do anything in the app settings or update anything. I thought it was a problem in the sever

**Comment by Atemu** [comment]
I don't think this app is on F-droid? Izzy has it in their repo IIRC but it's not in F-droid.

Install the latest APK from the release section.

**Comment by Bortex19** [comment]
I have imported the repo. I have the last version (0.22.1), it still crashes.

**Comment by XXDRD** [comment]
> I have imported the repo. I have the last version (0.22.1), it still crashes.

Occasional crashes after which you can't access the app are something I have experienced too, i.e. why I keep backups for all by data from newpipe

**Comment by Bortex19** [comment]
Have you any clue about why this happens or how could it be fixed?

**Comment by Atemu** [comment]
Only way to find out is look at the stacktrace in logcat.

As I said though, open a new issue.
