### ISSUE TITLE
A crash triggers when tapping ‘Video and Audio’ section in settings.

### ISSUE THREAD

**Issue by Jackie7610** [polymorphicshade/NewPipe#143]
The title says pretty much everything. Navigating through the app settings to ‘Video and Audio’ triggers a crash but this does not happen every single time. Sometimes I can access the ‘Video and Audio’. I have copied the error log. Here it is.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.22.0
* __OS:__ Linux Android 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.ListPreference.setEntryValues(java.lang.CharSequence[])' on a null object reference
	at org.schabi.newpipe.settings.VideoAudioSettingsFragment.updateSeekOptions(VideoAudioSettingsFragment.java:91)
	at org.schabi.newpipe.settings.VideoAudioSettingsFragment.onCreatePreferences(VideoAudioSettingsFragment.java:28)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
	at org.schabi.newpipe.settings.BasePreferenceFragment.onCreate(BasePreferenceFragment.java:28)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7025)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

```
</details>
<hr>

_Oh and this crash does not occur in the official Newpipe app_

**Comment by bloatmode** [comment]
This happens every time I click on "Video and audio" in my case.

**Comment by polymorphicshade** [comment]
Damn... yep I made a big mistake in the code. Expect a fix sometime today or tomorrow.
