### ISSUE TITLE
App crash on opening Sponsorblock Categories 

### ISSUE THREAD

**Issue by hbarsaiyan** [polymorphicshade/NewPipe#145]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.22.0 R1

### Steps to reproduce the bug

1. Go to Settings > Sponsorblock > Sponsorblock Categories 

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.22.0_r1
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:225)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2446)
	at android.content.res.Resources.getXml(Resources.java:1303)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:107)
	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
	at androidx.preference.PreferenceFragmentCompat.addPreferencesFromResource(PreferenceFragmentCompat.java:361)
	at org.schabi.newpipe.settings.BasePreferenceFragment.addPreferencesFromResourceRegistry(BasePreferenceFragment.java:32)
	at org.schabi.newpipe.settings.SponsorBlockCategoriesSettingsFragment.onCreatePreferences(SponsorBlockCategoriesSettingsFragment.java:24)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
	at org.schabi.newpipe.settings.BasePreferenceFragment.onCreate(BasePreferenceFragment.java:28)
	at org.schabi.newpipe.settings.SponsorBlockCategoriesSettingsFragment.onCreate(SponsorBlockCategoriesSettingsFragment.java:19)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

Mi 11X (aliothin)

**Comment by polymorphicshade** [comment]
![image](https://user-images.githubusercontent.com/32504507/155022439-65682ea4-6181-487b-8f58-aae9e70f7ae8.png)

**Comment by Atemu** [comment]
Merges are hard alright

Perhaps we should look into architectural changes to be less closely coupled with upstream's modules but I'm not sure how possible that is given the code quality and complexity of some parts we need to touch (player for example).

**Comment by hbarsaiyan** [comment]
@polymorphicshade fast af 🙃
