### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by cyberofficial** [polymorphicshade/NewPipe#159]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Play video
2. Update subscription by pull down
3. As subscriptions are updating resume video.

### Expected behavior

Refresh content in background.

### Actual behavior

Application crashes

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=1] occurred while playing https://www.youtube.com/watch?v=7bXWtXxLzlk
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.22.1
* __OS:__ Linux Android 6.0.1 - 23
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640020, -1, null, [1280, 720, -1.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1410)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:864)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
	... 3 more
Caused by: java.lang.IllegalStateException
	at android.media.MediaCodec.releaseOutputBuffer(Native Method)
	at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:2485)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.releaseOutputBuffer(SynchronousMediaCodecAdapter.java:155)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.renderOutputBufferV21(MediaCodecVideoRenderer.java:1156)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.processOutputBuffer(MediaCodecVideoRenderer.java:926)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1917)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:843)
	... 5 more

```
</details>
<hr>

### Affected device model

Samsung J3 (SM-J327P)

### Additional information

Device is rooted.

**Comment by Atemu** [comment]
Sounds like your hardware decoder is busted. Does that really not happen with upstream NewPipe?

Is this always reproducible?

**Comment by cyberofficial** [comment]
> Sounds like your hardware decoder is busted. Does that really not happen with upstream NewPipe?
> 
> Is this always reproducible?

Yea happen s only new pipe with sponsor block, I installed the one with out sponsor block, my actions work as intended, but with sponsor block, happens all 100% of the time

**Comment by cyberofficial** [comment]
Crashes randomly, but normal version works fine.

## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.22.1
* __OS:__ Linux Android 6.0.1 - 23
<details><summary><b>Crash log </b></summary><p>

```
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
	at android.database.CursorWindow.<init>(CursorWindow.java:108)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:300)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
	at org.schabi.newpipe.database.stream.dao.StreamDAO_Impl.getMinimalStreamForCompare$app_release(StreamDAO_Impl.java:889)
	at org.schabi.newpipe.database.stream.dao.StreamDAO.compareAndUpdateStream(StreamDAO.kt:87)
	at org.schabi.newpipe.database.stream.dao.StreamDAO.upsertAll(StreamDAO.kt:78)
	at org.schabi.newpipe.database.stream.dao.StreamDAO_Impl.access$101(StreamDAO_Impl.java:37)
	at org.schabi.newpipe.database.stream.dao.StreamDAO_Impl.upsertAll(StreamDAO_Impl.java:442)
	at org.schabi.newpipe.local.feed.FeedDatabaseManager.upsertAll(FeedDatabaseManager.kt:95)
	at org.schabi.newpipe.local.feed.FeedDatabaseManager.upsertAll$default(FeedDatabaseManager.kt:75)
	at org.schabi.newpipe.local.feed.service.FeedLoadService._get_databaseConsumer_$lambda-10$lambda-9(FeedLoadService.kt:321)
	at org.schabi.newpipe.local.feed.service.FeedLoadService.$r8$lambda$5AHZ_u5SBmOcx3ev880AHLHQo44(FeedLoadService.kt)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$$ExternalSyntheticLambda13.run(R8$$SyntheticClass)
	at androidx.room.RoomDatabase.runInTransaction(RoomDatabase.java:556)
	at org.schabi.newpipe.local.feed.service.FeedLoadService._get_databaseConsumer_$lambda-10(FeedLoadService.kt:314)
	at org.schabi.newpipe.local.feed.service.FeedLoadService.$r8$lambda$t9UFD3hMFrhHcyMOy0etirbfYQo(FeedLoadService.kt)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$$ExternalSyntheticLambda4.accept(R8$$SyntheticClass)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:86)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableBuffer$PublisherBufferExactSubscriber.onNext(FlowableBuffer.java:124)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:402)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

```
</details>
<hr>

**Comment by CarlosGS** [comment]
Can replicate too: when refreshing ~1200 subscriptions while playing a video, it starts to stutter when about 900 feeds have been loaded, and it gets worse and worse until the app freezes completely.

Sometimes it produces an Out Of Memory error, and indeed RAM consumption seems to peak ~400MB more than the upstream version. This refresh process also takes at least double the time in this fork and loading feels a bit more "jittery". Not sure what could cause refreshing to use more resources here :thinking:

**Comment by polymorphicshade** [comment]
@cyberofficial try out the latest version and see if you still have the same issue.

**Comment by cyberofficial** [comment]
> @cyberofficial try out the latest version and see if you still have the same issue.

Seems to be fixed now. No issues when using it for the past 40 minutes
