### ISSUE TITLE
'App/UI crashed' during subscription import

### ISSUE THREAD

**Issue by rilesbriles** [polymorphicshade/NewPipe#168]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Press import
2. Select zip or csv file

### Expected behavior

Import my subscriptions

### Actual behavior

Gives error

### Logs

-------------------------------------
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@a3fc4e0 with Intent { cmp=org.polymorphicshade.newpipe/org.schabi.newpipe.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{2713809 14037:org.polymorphicshade.newpipe/u0a495} (pid=14037, uid=10495) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4536)
	at android.app.ActivityThread.access$2200(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8035)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{2713809 14037:org.polymorphicshade.newpipe/u0a495} (pid=14037, uid=10495) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5855)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7136)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2954)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2525)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1819)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1650)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1597)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
	at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:118)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4518)
	... 8 more
-------------------------------------

### Affected Android/Custom ROM version

Android 11

### Affected device model

Oneplus 9 pro

**Comment by prestonpirateking** [comment]
I also have this error

**Comment by downloadkct** [comment]
Same here, the regular version of newpipe works great while importing.

**Comment by gmferise** [comment]
Also experiencing this. I tried checking the storage permission for the app but no luck. The only one available to enable says "Allow access to media only", so I think the wrong permission is requested. Zip and CSV likely require another permission.

**Comment by MDP43140** [comment]
I have the same problem too, but mine was caused by importing to [this debug apk (removed)](https://github.com/TeamNewPipe/NewPipe/issues/8202), exporting it, and importing it on version 0.22.2. importing older settings/subscriptions won't cause this issue though, so if you have older backups, you can try importing that and see if its not crashed...

**Comment by polymorphicshade** [comment]
I can't reproduce this issue. Try using the latest release of my fork. If you can consistently reproduce this problem I'll re-open this issue.
