### ISSUE TITLE
Videos not playing 

### ISSUE THREAD

**Issue by Tintedfireglass** [polymorphicshade/NewPipe#173]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1 sponsorblock

### Steps to reproduce the bug

1. Open newpipe
2. Click on any video

### Expected behavior

A video should start playing

### Actual behavior

But I get an error message asking me to  raise a bug report and a sad face appears where the video had to play.  

### Screenshots/Screen recordings

Screen recording : https://media.discordapp.net/attachments/884641872008577064/964362126288379934/screen-20220415-083644.mp4

SCREENSHOT : https://media.discordapp.net/attachments/884641872008577064/964362126837837975/Screenshot_20220415-083756.png

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=WyJDimr_BJ0
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.22.1
* __OS:__ Linux motorola/hanoip_retailnq/hanoip:11/RRI31.Q1-42-51-12/c157c:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11

### Affected device model

Motorola G60

**Comment by Tintedfireglass** [comment]
I can provide more information if required :)

**Comment by briaguya-ai** [comment]
I also encountered this issue, but I *was* able to reproduce it on upstream (0.22.1 from fdroid standard repo)

My guess is it's https://github.com/TeamNewPipe/NewPipe/issues/8202

**Comment by TacoTheDank** [comment]
Yeah this is https://github.com/TeamNewPipe/NewPipe/issues/8202, it'll be fixed ASAP

**Comment by Tintedfireglass** [comment]
Ohh looks like I had an older newpipe(upstream) version

Yeah it is an upstream bug😅

**Comment by Aurangzeb365** [comment]
> Ohh looks like I had an older newpipe(upstream) version
> 
> Yeah it is an upstream bug😅

Is it fixed?

**Comment by Tintedfireglass** [comment]
> > Ohh looks like I had an older newpipe(upstream) version
> > 
> > Yeah it is an upstream bug😅
> 
> Is it fixed?
> 

It will be fixed with an emergency minor  update I think as something similar happened a couple of months ago (maybe something to do with Google apis I guess I'm not sure)

**Comment by xorbital** [comment]
Upstream version v0.22.2 now includes the necessary changes

**Comment by Aurangzeb365** [comment]
> Upstream version v0.22.2 now includes the necessary changes

what about extractor?

**Comment by Aurangzeb365** [comment]
org.schabi.newpipe.extractor.playlist.PlaylistInfoItem cannot be cast to org.schabi.newpipe.extractor.stream.StreamInfoItem
i'm getting this error after update.
Can you guide?

**Comment by Atemu** [comment]
0.22.2 includes the extractor update (and little else).

We'll have to wait for @polymorphicshade to merge upstream master.

**Comment by polymorphicshade** [comment]
The [latest release](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.22.2) should have the fix implemented.
