### ISSUE TITLE
Random Errors, Latest Release

### ISSUE THREAD

**Issue by grravity** [polymorphicshade/NewPipe#18]
```
-------------------------------------
java.lang.RuntimeException: Error receiving broadcast Intent { act=org.schabi.newpipe.VideoDetailFragment.ACTION_PLAYER_STARTED flg=0x10 } in org.schabi.newpipe.fragments.detail.VideoDetailFragment$4@7b000b7
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1606)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7615)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.polymorphicshade.newpipe/org.schabi.newpipe.player.MainPlayer }: app is in background uid UidRecord{cc860df u0a352 CAC  bg:+15m2s693ms idle change:idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1637)
	at android.app.ContextImpl.startService(ContextImpl.java:1592)
	at android.content.ContextWrapper.startService(ContextWrapper.java:669)
	at org.schabi.newpipe.player.helper.PlayerHolder.startService(PlayerHolder.java:88)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$4.onReceive(VideoDetailFragment.java:1404)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1588)
	... 8 more
-------------------------------------
```

**Comment by B0pol** [comment]
See https://github.com/TeamNewPipe/NewPipe/issues/4653
I'll fix it upstream

**Comment by polymorphicshade** [comment]
@B0pol I believe this should be fixed now right?

**Comment by B0pol** [comment]
Right now, with https://github.com/TeamNewPipe/NewPipe/pull/5221 merged, it should be fixed.
