### ISSUE TITLE
UI crash when lauching a video

### ISSUE THREAD

**Issue by BhasherBEL** [polymorphicshade/NewPipe#191]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.1.4

### Steps to reproduce the bug

1. Open the app
2. Click on a video
3. Crash

### Expected behavior

Lauching video

### Actual behavior

The apps seems restart multiple time before crash

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ FR
* __Content Language:__ fr
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.1.4
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service org.schabi.newpipe.player.MainPlayer: java.lang.NumberFormatException: For input string: "default"
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4198)
	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NumberFormatException: For input string: "default"
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.parseInt(Integer.java:650)
	at org.schabi.newpipe.player.helper.PlayerHelper.getProgressiveLoadIntervalBytes(PlayerHelper.java:434)
	at org.schabi.newpipe.player.helper.PlayerDataSource.<init>(PlayerDataSource.java:42)
	at org.schabi.newpipe.player.Player.<init>(Player.java:451)
	at org.schabi.newpipe.player.MainPlayer.createView(MainPlayer.java:106)
	at org.schabi.newpipe.player.MainPlayer.onCreate(MainPlayer.java:100)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4186)
	... 8 more

```
</details>
<hr>

### Affected Android/Custom ROM version

LineageOS 18.1

### Affected device model

Xiaomi redmi note 9 pro

### Additional information

The bug append just after the update to the very last version.

**Comment by juandarr** [comment]
I am having the same problem. Issue wasn´t present in previous release.

**Comment by polymorphicshade** [comment]
Try installing the latest release of my fork and see if you get the same issue. If you do, I'll re-open this issue.
