### ISSUE TITLE
Unable to export backup

### ISSUE THREAD

**Issue by vukhidalgo** [polymorphicshade/NewPipe#202]
Hi! :blush: I'm having issues when exporting a backup of my subscriptions to a local folder or to a remote Google Drive one. I'm using Android's default file manager for this purpose. As a side note, I would like to thank you for this amazing app. Here's the report:

-------

## Exception
* __User Action:__ ui error
* __Request:__ Exporting database
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

-------

```
java.io.FileNotFoundException: Unsupported mode: rw
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1816)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1631)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1578)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
	at org.schabi.newpipe.settings.ContentSettingsManager.exportDatabase(ContentSettingsManager.kt:28)
	at org.schabi.newpipe.settings.ContentSettingsFragment.exportDatabase(ContentSettingsFragment.java:197)
	at org.schabi.newpipe.settings.ContentSettingsFragment.requestExportPathResult(ContentSettingsFragment.java:166)
	at org.schabi.newpipe.settings.ContentSettingsFragment.$r8$lambda$8bBkxkdGnhK6YvPK6sE5N6ky1yA(Unknown Source:0)
	at org.schabi.newpipe.settings.ContentSettingsFragment$$ExternalSyntheticLambda4.onActivityResult(Unknown Source:4)
	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3026)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8018)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

**Comment by polymorphicshade** [comment]
This isn't relevant to my fork - please report this issue upstream.
