### ISSUE TITLE
Automatic video quality.

### ISSUE THREAD

**Issue by Broniy** [polymorphicshade/NewPipe#211]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Automatic video quality for fast and comfortable watching of videos.

### Why do you want this feature?

To watch videos comfortably.

### Why ist the feature relevant to this fork?

I think it can be added.

### Additional information

No

**Comment by Atemu** [comment]
Ask upstream, it's not relevant to this fork.

**Comment by Broniy** [comment]
They don't want to add it.

**Comment by Atemu** [comment]
That would have been valuable info to add to your issue, along with a link where they explain why.

**Comment by Atemu** [comment]
If I was to add it, I'd add it to upstream Newpipe.   

This fork only exists for features for features which upstream explicitly does *not* want for non-technical reasons.  
This is what happened with Sponsorblock and that's why the fork exists. We don't have any bad blood with upstream and  this isn't a hard fork either. It only exists to add a few features on top of upstream NewPipe. Anything upstream gets, we get too (+ our extra features).

Why was the feature rejected upstream?

**Comment by Nizami20052022** [comment]
He is right, they don't do it yet.

**Comment by Atemu** [comment]
Did they just not do it yet or are they *explicitly against* doing it?

This is not the place to ask for stale upstream feature request.

**Comment by Nizami20052022** [comment]
I reported this feature to them and they said they won't add it.

**Comment by Sagarparvizali** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.23.1_r1
* __OS:__ Linux samsung/a20sxx/a20s:11/RP1A.200720.012/A207FXXU3CUL1:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.SecurityException: UID 10778 does not have permission to content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FNewPipe%20%2FI%20Used%20to%20Ask%20the%20Messenger%20%EF%B7%BA%20About%20The%20Evil%20Lesson%20By%20Abu%20Hakeem%20Bilal%20Davis.mp3 [user 0] [prefix]; you could obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
	at android.os.Parcel.createException(Parcel.java:2369)
	at android.os.Parcel.readException(Parcel.java:2352)
	at android.os.Parcel.readException(Parcel.java:2294)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:4276)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1723)
	at android.app.Activity.startActivityForResult(Activity.java:5377)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at android.app.Activity.startActivityForResult(Activity.java:5335)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
	at android.app.Activity.startActivity(Activity.java:5721)
	at android.app.Activity.startActivity(Activity.java:5674)
	at org.schabi.newpipe.util.external_communication.ShareUtils.openIntentInApp(ShareUtils.java:157)
	at us.shandian.giga.ui.adapter.MissionAdapter.openExternally(MissionAdapter.java:388)
	at us.shandian.giga.ui.adapter.MissionAdapter.-$$Nest$mopenExternally(Unknown Source:0)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem.lambda$new$1(MissionAdapter.java:935)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem.$r8$lambda$PAQE6UWV_7gFHr9RCCIksMCusOo(Unknown Source:0)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:8160)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1265)
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:617)
	at com.android.server.uri.UriGrantsManagerService.access$1000(UriGrantsManagerService.java:117)
	at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermissionFromIntent(UriGrantsManagerService.java:1427)
	at com.android.server.wm.ActivityStarter$Request.resolveActivity(ActivityStarter.java:657)


```
</details>
<hr>

**Comment by SameenAhnaf** [comment]
Nobody said that https://github.com/TeamNewPipe/NewPipe/issues/8444 won't be added. https://github.com/TeamNewPipe/NewPipe/issues/5323 already asks for the same feature. That's why, the duplicate issue was closed.

> - [ ] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at NewPipeExtractor.
> - [ ]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.

@Nizami20052022 Please consider following the checklist. Try searching issues for issues (maybe, with better keywords). If you want to emphasize any issue, just upvote that issue. 

Your issue was not closed in favor of rejection. Rather, we don't want to bloat the repo with similar issues.

**Comment by SameenAhnaf** [comment]
>You closed the issue as "Not planned".

This issue was closed way before GitHub implemented "solved" or "not planned". For old issues, GitHub randomly chooses "solved" or "not planned".

**Comment by SavageTheUnicorn** [comment]
The close as duplicate feature was added in 2017ish. This issue was opened in 2020.

**Comment by mhmdanas** [comment]
I'm speaking about this feature: https://github.blog/changelog/2022-03-10-the-new-github-issues-march-10th-update/#%F0%9F%95%B5%F0%9F%8F%BD%E2%99%80%EF%B8%8F-issue-closed-reasons

**Comment by SavageTheUnicorn** [comment]
@mhmdanas I was not aware of that feature. Thank you for the information.

**Comment by polymorphicshade** [comment]
I have no plans on doing this, though if anyone else wants to give it a shot I'll be happy to merge in their changes.
