### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by cohesive-flight** [polymorphicshade/NewPipe#216]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. Search for a video (likely optional)
2. Click on a video
3. Rotate the screen quickly while the video is buffering

(not reliable; only managed to make it appear once more after the initial crash)

### Expected behavior

For the video to finish buffering and play.

### Actual behavior

The application crashed, and continues to do so on startup until it's reinstalled.

### Screenshots/Screen recordings

[newpipexsb_startup-crash.zip](https://github.com/polymorphicshade/NewPipe/files/9180510/newpipexsb_startup-crash.zip)

### Logs

The error report page did not appear on the initial crash nor the subsequent startup crashes. Thus, I decided to use logcat instead to retrieve the logs of when it crashes on startup (it doesn't seem to be properly formatted when pasted on GitHub, so I attached a zip of the logs with proper formatting in the screenshot area).

--------- beginning of crash
07-25 06:11:34.316 15900 18341 E AndroidRuntime: FATAL EXCEPTION: Thread-4
07-25 06:11:34.316 15900 18341 E AndroidRuntime: Process: org.polymorphicshade.newpipe, PID: 15900
07-25 06:11:34.316 15900 18341 E AndroidRuntime: java.lang.IllegalArgumentException: Tried to schedule job for non-existent component: ComponentInfo{org.polymorphicshade.newpipe/org.acra.sender.JobSenderService}
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2430)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2410)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2393)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2335)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:312)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:52)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at org.acra.startup.StartupProcessorExecutor.processReports$lambda-5$lambda-4(StartupProcessorExecutor.kt:56)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at org.acra.startup.StartupProcessorExecutor.$r8$lambda$o2NE53IEwtcT_aLpWXA2a4JC9OE(Unknown Source:0)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda1.run(Unknown Source:6)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2713)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2766)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:155)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1143)
07-25 06:11:34.316 15900 18341 E AndroidRuntime: 
07-25 06:11:34.317 15900 18341 E ACRA    : ACRA caught a IllegalArgumentException for org.polymorphicshade.newpipe
07-25 06:11:34.317 15900 18341 E ACRA    : java.lang.IllegalArgumentException: Tried to schedule job for non-existent component: ComponentInfo{org.polymorphicshade.newpipe/org.acra.sender.JobSenderService}
07-25 06:11:34.317 15900 18341 E ACRA    : 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2430)
07-25 06:11:34.317 15900 18341 E ACRA    : 	at android.os.Parcel.createException(Parcel.java:2410)
07-25 06:11:34.317 15900 18341 E ACRA    : 	at android.os.Parcel.readException(Parcel.java:2393)
07-25 06:11:34.317 15900 18341 E ACRA    : 	at android.os.Parcel.readException(Parcel.java:2335)
07-25 06:11:34.317 15900 18341 E ACRA    : 	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:312)
07-25 06:11:34.317 15900 18341 E ACRA    : 	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47)
07-25 06:11:34.317 15900 18341 E ACRA    : 	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:52)
07-25 06:11:34.317 15900 18341 E ACRA    : 	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49)
07-25 06:11:34.317 15900 18341 E ACRA    : 	at org.acra.startup.StartupProcessorExecutor.processReports$lambda-5$lambda-4(StartupProcessorExecutor.kt:56)
07-25 06:11:34.317 15900 18341 E ACRA    : 	at org.acra.startup.StartupProcessorExecutor.$r8$lambda$o2NE53IEwtcT_aLpWXA2a4JC9OE(Unknown Source:0)
07-25 06:11:34.317 15900 18341 E ACRA    : 	at org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda1.run(Unknown Source:6)
07-25 06:11:34.317 15900 18341 E ACRA    : 	at java.lang.Thread.run(Thread.java:920)
07-25 06:11:34.317 15900 18341 E ACRA    : Caused by: android.os.RemoteException: Remote stack trace:
07-25 06:11:34.317 15900 18341 E ACRA    : 	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2713)
07-25 06:11:34.317 15900 18341 E ACRA    : 	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2766)
07-25 06:11:34.317 15900 18341 E ACRA    : 	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:155)
07-25 06:11:34.317 15900 18341 E ACRA    : 	at android.os.Binder.execTransactInternal(Binder.java:1179)
07-25 06:11:34.317 15900 18341 E ACRA    : 	at android.os.Binder.execTransact(Binder.java:1143)
07-25 06:11:34.317 15900 18341 E ACRA    : 
07-25 06:11:34.356 15900 18336 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
07-25 06:11:34.357 15900 18371 I Gralloc4: mapper 4.x is not supported
07-25 06:11:34.357 15900 18371 W Gralloc3: mapper 3.x is not supported
07-25 06:11:34.359 15900 18371 I gralloc : Arm Module v1.0
07-25 06:11:34.360 15900 18371 W Gralloc4: allocator 4.x is not supported
07-25 06:11:34.360 15900 18371 W Gralloc3: allocator 3.x is not supported
07-25 06:11:34.364 15900 18371 I Gralloc2: Adding additional valid usage bits: 0x0
07-25 06:11:34.341 15900 15900 W RenderThread: type=1400 audit(0.0:11258): avc: denied { search } for name="data" dev="sda31" ino=2015233 scontext=u:r:untrusted_app_29:s0:c245,c256,c522,c768 tcontext=u:object_r:system_data_file:s0:c512,c768 tclass=dir permissive=0
07-25 06:11:34.341 15900 15900 W RenderThread: type=1300 audit(0.0:11258): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=6f1c37d330 a2=0 a3=0 items=0 ppid=5958 auid=4294967295 uid=1010245 gid=1010245 euid=1010245 suid=1010245 fsuid=1010245 egid=1010245 sgid=1010245 fsgid=1010245 tty=(none) ses=4294967295 exe="/system/bin/app_process64" subj=u:r:untrusted_app_29:s0:c245,c256,c522,c768 key=(null)
07-25 06:11:34.380 15900 18376 D CompatibilityChangeReporter: Compat change id reported: 149924527; UID 1010245; state: ENABLED
07-25 06:11:34.380 15900 18376 D CompatibilityChangeReporter: Compat change id reported: 132649864; UID 1010245; state: DISABLED
07-25 06:11:34.398 15900 18324 I OpenGLRenderer: Davey! duration=9222746430967ms; Flags=1, FrameTimelineVsyncId=35134511, IntendedVsync=625605887363767, Vsync=625605887363767, InputEventId=0, HandleInputStart=625605887798800, AnimationStart=625605887799647, PerformTraversalsStart=625605887800339, DrawStart=625605935582954, FrameDeadline=625605904030433, FrameInterval=625605887795493, FrameStartTime=16666666, SyncQueued=625605937388531, SyncStart=625605937452877, IssueDrawCommandsStart=625605938418724, SwapBuffers=625605968689493, FrameCompleted=9223372036854775807, DequeueBufferDuration=3509192, QueueBufferDuration=1487769, GpuCompleted=9223372036854775807, SwapBuffersCompleted=625605970560839, DisplayPresentTime=0, 
07-25 06:11:34.469 15900 18349 E class org.schabi.newpipe.App: RxJavaPlugins.ErrorHandler called with -> : throwable = [io.reactivex.rxjava3.exceptions.UndeliverableException]
07-25 06:11:34.509 15900 18341 E ACRA    : ACRA failed to capture the error - handing off to native error reporter
07-25 06:11:34.509 15900 18341 E ACRA    : java.lang.IllegalArgumentException: Tried to schedule job for non-existent component: ComponentInfo{org.polymorphicshade.newpipe/org.acra.sender.JobSenderService}
07-25 06:11:34.509 15900 18341 E ACRA    : 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2430)
07-25 06:11:34.509 15900 18341 E ACRA    : 	at android.os.Parcel.createException(Parcel.java:2410)
07-25 06:11:34.509 15900 18341 E ACRA    : 	at android.os.Parcel.readException(Parcel.java:2393)
07-25 06:11:34.509 15900 18341 E ACRA    : 	at android.os.Parcel.readException(Parcel.java:2335)
07-25 06:11:34.509 15900 18341 E ACRA    : 	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:312)
07-25 06:11:34.509 15900 18341 E ACRA    : 	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47)
07-25 06:11:34.509 15900 18341 E ACRA    : 	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:52)
07-25 06:11:34.509 15900 18341 E ACRA    : 	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49)
07-25 06:11:34.509 15900 18341 E ACRA    : 	at org.acra.builder.ReportExecutor.sendReport(ReportExecutor.kt:197)
07-25 06:11:34.509 15900 18341 E ACRA    : 	at org.acra.builder.ReportExecutor.execute(ReportExecutor.kt:135)
07-25 06:11:34.509 15900 18341 E ACRA    : 	at org.acra.builder.ReportBuilder.build(ReportBuilder.kt:151)
07-25 06:11:34.509 15900 18341 E ACRA    : 	at org.acra.reporter.ErrorReporterImpl.uncaughtException(ErrorReporterImpl.kt:105)
07-25 06:11:34.509 15900 18341 E ACRA    : 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
07-25 06:11:34.509 15900 18341 E ACRA    : 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
07-25 06:11:34.509 15900 18341 E ACRA    : 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)
07-25 06:11:34.509 15900 18341 I ACRA    : ACRA is disabled for org.polymorphicshade.newpipe - forwarding uncaught Exception on to default ExceptionHandler
07-25 06:11:34.524 15900 18341 I Process : Sending signal. PID: 15900 SIG: 9

### Affected Android/Custom ROM version

LineageOS 19.1

### Affected device model

Samsung Galaxy S10+

**Comment by polymorphicshade** [comment]
@cohesive-flight try out the latest version and see if you still have the same issue.

**Comment by cohesive-flight** [comment]
> @cohesive-flight try out the latest version and see if you still have the same issue.

Honestly, I haven't experienced this issue since then. I've always been using the latest version, so maybe it's been fixed by one of the recent updates. 

Also, this bug might be prevalent in the original Newpipe, as the method to produce it is unreliable (so it goes unnoticed).

**Comment by anon97945** [comment]
I also have the problem of crash while rotation. It's very annoying and i have it since android 12 on my pixel 6.

**Comment by Atemu** [comment]
@anon97945 are you able to reproduce it in regular NewPipe?

**Comment by TadaCZE** [comment]
I reproduced it, also android 12, crDroid on chime (Poco M3), also the crash report: https://paste.crdroid.net/FuQNDp

**Comment by Atemu** [comment]
> are you able to reproduce it in regular NewPipe?

**Comment by cohesive-flight** [comment]
I can confirm this issue is reproducible with regular NewPipe, but I'm not sure if it's exactly the same, as I missed the output, and nothing is returned from grep when searching for similar lines in logcat.

Also, there's a similar issue open for regular NewPipe (TeamNewPipe/NewPipe/issues/9277).

**Comment by cohesive-flight** [comment]
It is reproducible with v0.24.1 of this fork and regular NewPipe.

**Comment by d4f5409d** [comment]
Same issue here. 0.24.1 Sponsorblock version.
Logs:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ HU
* __Content Language:__ hu
* __App Language:__ hu_HU
* __Service:__ none
* __Version:__ 0.24.1
* __OS:__ Linux OnePlus/OnePlus8/OnePlus8:13
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$handleResult$23(VideoDetailFragment.java:1626)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$kvbSCZYpk1eZXvjw0VQVcbHCIUo(Unknown Source:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda38.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

**Comment by g1t3m** [comment]
I can attest to this issue of Newpipe crashing whenever I expand the video to fullscreen when pressing the fullscreen button. It doesn't happen on all videos, but once in a while. 

In the first scenario, I turned off the "start main player in fullscreen" setting prior to this, and disabled my phone's auto-rotate setting to reproduce this. So far this hasn't occurred woth these settings disabled.

In the next scenario, I kept the "Start main player in fullscreen" setting disabled and enabled my phone's auto rotate setting. So far this issue has not occurred.

Final scenario, I enabled both the "Start main player in fullscreen" and my phone's auto rotate setting. This issue hasn't occurred yet.

So far, this issue hasn't occurred today, but it did happen yesterday for a few videos I tried to play. I will update this comment with the exact settings I enabled if I am able to reproduce this issue.
