### ISSUE TITLE
Sorry something went wrong error

### ISSUE THREAD

**Issue by NOOBNOOBOX** [polymorphicshade/NewPipe#226]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1 latest version

### Steps to reproduce the bug

1. Go to subscriptions
2. Play any video
3. Error

### Expected behavior

Video to play normally

### Actual behavior

Video doesn't play, showing error

### Screenshots/Screen recordings

<img alt="IMG_20220812_172521" src="https://user-images.githubusercontent.com/71785303/184363131-ef6c6dc2-76fa-4ea6-841a-6c10eda0eb91.jpg" height=600 />

<img alt="IMG_20220812_172926" src="https://user-images.githubusercontent.com/71785303/184363845-ae6851d2-39d1-40e5-9e48-795ba42682df.jpg" height=600 />

### Logs

-------------------------------------
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:188)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:82)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
-------------------------------------

### Affected Android/Custom ROM version

Android 12 / miui 13

### Affected device model

Redmi note 9

**Comment by iprok** [comment]
Hello. I confirm the issue. The reported problem relates to any video. No one can be played.

**Comment by schtiehve** [comment]
Seems YouTube changed something again. 

Upstream Issue: https://github.com/TeamNewPipe/NewPipe/issues/8760

Let's hope the extractor gets an update soon

**Comment by ifeelagood** [comment]
Wow I literally installed the app 3 minutes ago. Fuck

**Comment by TDavLinguist** [comment]
Looks like someone over on NewPipe has fixed it with a pull request. We just have to wait for them to release it into main.
https://github.com/TeamNewPipe/NewPipeExtractor/pull/891

**Comment by nebakanezzer** [comment]
The debug apk in that merge works if you don't want to wait

**Comment by emilianosalatino** [comment]
Fuckin miiiiinttt

**Comment by IntoTheVoid-900** [comment]
How long until the PR will be merged here?

**Comment by TDavLinguist** [comment]
> 

If you have Android Studio, just git clone the polymorphicshade/NewPipe repo and the upstream NewPipeExtractor repo into the same parent directory
So
`/foo/NewPipeExtractor` (upstream)
and
`/foo/NewPipe` (polymorphicshade)

Then follow the instructions on [this page](https://teamnewpipe.github.io/documentation/04_Run_changes_in_App/) to build a debug APK and voila! I'd do it myself, but my computer is a weak potato that wouldn't survive the build process.

**Comment by orariley70** [comment]
I compiled the debug variant (it works, but you should really switch to normal (release) APK once the maintainer has released the new update), so your computer doesn't need to suffer like mine did.
[org.polymorphicshade.newpipe.debug.sponsorblock 0.23.2 APK.zip](https://github.com/polymorphicshade/NewPipe/files/9331241/org.polymorphicshade.newpipe.debug.sponsorblock.0.23.2.APK.zip)

**Comment by TDavLinguist** [comment]
> I compiled the debug variant (it works, but you should really switch to normal (release) APK once the maintainer has released the new update), so your computer doesn't need to suffer like mine did. [org.polymorphicshade.newpipe.debug.sponsorblock 0.23.2 APK.zip](https://github.com/polymorphicshade/NewPipe/files/9331241/org.polymorphicshade.newpipe.debug.sponsorblock.0.23.2.APK.zip)

Hey, thanks! I actually tried to compile with Gradle from the CLI and it failed at 86%. So I'm glad it worked for you!

**Comment by codingicebear** [comment]
Dev @polymorphicshade do your honors 🥺🤲

**Comment by west89** [comment]
Is fixed in the original version.
https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.23.2

**Comment by polymorphicshade** [comment]
This should now be fixed in the latest version.
