### ISSUE TITLE
Random, Constant Erroneous "Not Responding" Dialogs

### ISSUE THREAD

**Issue by gudenau** [polymorphicshade/NewPipe#255]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Watch some videos
2. Randomly a ANR dialogue will spawn during a video
3. Every few seconds after dismissing an ANR will spawn
4. Kill application to stop it

### Expected behavior

No ANR dialogues.

### Actual behavior

ANR dialogue spam.

### Screenshots/Screen recordings

https://youtu.be/34OhRUYLms8

### Logs

N/A, no crashes.

### Affected Android/Custom ROM version

"Stock" Android Tiramisu, Magisk 25.2

### Affected device model

Pixel 4 XL

### Additional information

I have not noticed any specific patterns to this behavior, as far as I can tell it's random while a video is being played.

**Comment by Atemu** [comment]
Are you able to reproduce the issue in upstream NewPipe?

**Comment by gudenau** [comment]
I played around with it some and it didn't happen, but since it's random it might have not triggered.

**Comment by gudenau** [comment]
I just got this crash when the spam started, might it be related?

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{a296f23 u0 org.polymorphicshade.newpipe/org.schabi.newpipe.player.PlayerService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2006)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1977)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1915)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1870)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openMainPlayer(VideoDetailFragment.java:1244)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$7cA0nfOW4EXxLpA03fs92UQohwM(Unknown Source:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda17.run(Unknown Source:2)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.replaceQueueIfUserConfirms(VideoDetailFragment.java:2191)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openVideoPlayer(VideoDetailFragment.java:1199)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openVideoPlayerAutoFullscreen(VideoDetailFragment.java:1212)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$runWorker$9(VideoDetailFragment.java:951)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$U48iIKXy1FeNEKzrs0mKI60q5_s(Unknown Source:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda13.accept(Unknown Source:8)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	... 6 more

```
</details>
<hr>

**Comment by gudenau** [comment]
Okay after paying more attention to what I'm doing it appears that you need to:
- Watch a video from your subscriptions (maybe in fullscreen) until the end
- Minimize the video
- Start another video from your subscriptions
- Maybe have the ANR spam after a few minutes

I'm not sure if this is related to the sponsor block functionality or not, I'll test it on upstream when I have more time.

**Comment by Atemu** [comment]
@gudenau I've never had this happen. I'm on LineageOS 19.1 (Android 12) with Magisk 25.2 aswell.

I see that you're on Android 13. Did this use to happen on Android 12?

The crash report you got is related to foreground services. Perhaps Google changed something about them in Android 13.

**Comment by Hypnoticbat9555** [comment]
I got the same on Version 0.24 on the original newpipe. Had to switch back to version 0.23 for now

**Comment by Hypnoticbat9555** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/9070#issuecomment-1268012889

**Comment by Atemu** [comment]
This can be closed then.

**Comment by gudenau** [comment]
I thought I figured it out but now it stopped doing it, but I'll post what it seemed to be anyway in case it's a network issue:
- Watch video
- Don't dismiss it with the X
- Watch another video
- ANR after a few seconds

**Comment by gudenau** [comment]
> * revert to https://github.com/polymorphicshade/NewPipe/releases/tag/v0.23.3
> 
> 
> also,
> 
>     * make sure you are NOT using mp4 and m4a.
> 
>     * replace the [sponsorblock api server](https://gist.github.com/eladkarako/e0ffe9dfaa3d41f61b68d8e4e7158f38#file-sponsorblock-mirrors-both-db-and-api-txt) to reduces hangs.

I always use the MPEG-4 streams.

**Comment by gudenau** [comment]
It appears to be fixed, I'll tentatively close this.

**Comment by gudenau** [comment]
![Screenshot_20221120-145436](https://user-images.githubusercontent.com/5642329/202925661-a9d5b94a-4ecc-4a63-8c3c-36088eb46cdf.png)
Unfortunately it still occurs.
