### ISSUE TITLE
Player crashes when "Auto Fullscreen" is enabled

### ISSUE THREAD

**Issue by ItamiWasTaken** [polymorphicshade/NewPipe#268]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$handleResult$23(VideoDetailFragment.java:1619)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$kvbSCZYpk1eZXvjw0VQVcbHCIUo(Unknown Source:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda23.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

**Comment by Atemu** [comment]
Please use the template.
