### ISSUE TITLE
crash when running downloaded audio

### ISSUE THREAD

**Issue by truong0235** [polymorphicshade/NewPipe#272]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

newest 

### Steps to reproduce the bug

open app
go to download
run an audio
app crashes and reopens with error page

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.SecurityException: UID 10319 does not have permission to content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fnewpipe%2FRex%20Incognito.m4a [user 0] [prefix]; you could obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3969)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1734)
	at android.app.Activity.startActivityForResult(Activity.java:5430)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at android.app.Activity.startActivityForResult(Activity.java:5388)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
	at android.app.Activity.startActivity(Activity.java:5774)
	at android.app.Activity.startActivity(Activity.java:5727)
	at org.schabi.newpipe.util.external_communication.ShareUtils.openIntentInApp(ShareUtils.java:157)
	at us.shandian.giga.ui.adapter.MissionAdapter.openExternally(MissionAdapter.java:386)
	at us.shandian.giga.ui.adapter.MissionAdapter.-$$Nest$mopenExternally(Unknown Source:0)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem.lambda$new$1(MissionAdapter.java:933)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem.$r8$lambda$PAQE6UWV_7gFHr9RCCIksMCusOo(Unknown Source:0)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7735)
	at android.view.View.performClickInternal(View.java:7712)
	at android.view.View.access$3600(View.java:848)
	at android.view.View$PerformClick.run(View.java:28971)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8114)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1290)
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:628)
	at com.android.server.uri.UriGrantsManagerService.access$1000(UriGrantsManagerService.java:121)
	at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermissionFromIntent(UriGrantsManagerService.java:1463)
	at com.android.server.wm.ActivityStarter$Request.resolveActivity(ActivityStarter.java:589)


```
</details>
<hr>

### Affected Android/Custom ROM version

MIUI poco rom

### Affected device model

Poco c40

**Comment by Atemu** [comment]
You haven't given the app permission for the directory you're trying to download to. This has nothing to do with our fork.

**Comment by truong0235** [comment]
@Atemu still getting crash after give app storage perm

**Comment by truong0235** [comment]
same result
so shoud i close this and bring this one to upstream one on github?

**Comment by Atemu** [comment]
Yes.
