### ISSUE TITLE
Network error on sponsor segments

### ISSUE THREAD

**Issue by limejet** [polymorphicshade/NewPipe#339]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

1. open [the video with sponsorblock segments](https://www.youtube.com/watch?v=xHmgHjvv1Hk) mentioned in the crash log
2. play the video until the first segment (fittingly, it's just after Colin goes "we need a plan! and a sponsor!" at 0:40)

### Expected behavior

the video should skip the sponsorblock segment and keep playing.

### Actual behavior

The segment is skipped, but the player then immediately throws a network error and stops. trying to resume results in another immediate error. mashing the jog buttons sometimes makes the video play again, but it's hard to reproduce.

### Screenshots/Screen recordings

/

https://github.com/polymorphicshade/NewPipe/assets/4407285/03a3ad7c-4f3b-45f6-a182-cc85257e1380

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=xHmgHjvv1Hk
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.25.1
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:346)
	at android.os.Looper.loop(Looper.java:475)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13, build 64.1.A.0.929, kernel 5.10.136-android12756862

### Affected device model

Sony Xperia 5 IV (model number XQ-CQ54)

### Additional information

only thing that may be relevant is that this is on hotel wifi, so it may be congested? It's not to any noticeable degree though.

**Comment by limejet** [comment]
An update: this was not reproducible after waiting a few hours. Considering that the error is question seems to be a 403, is there a possibility that this has something to do with the new youtube thing where they limit the number of videos you can watch per day with an ad blocker? in that case I guess this is an upstream issue.

**Comment by Atemu** [comment]
This is a general NewPipe error. The sponsor skip just happens to trigger it because it's a skip.
