### ISSUE TITLE
App crashed render issues on history

### ISSUE THREAD

**Issue by VitoItalianGamer** [polymorphicshade/NewPipe#343]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

1. Go to history
2. Scroll down
3. Play video
4. Rotate back and forth
5. Minimize video
6. Then scroll up when rendering issues happen

### Expected behavior

Does not have rendering issues when scrolling up and does not crash.

### Actual behavior

When scrolling up the app crashes 

### Screenshots/Screen recordings

![Screenshot_20230723-124219](https://github.com/polymorphicshade/NewPipe/assets/138238777/01a48c00-82a7-4ede-8e26-2f0c26a592a8)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.1
* __OS:__ Linux motorola/tonga_g/tonga:12/S3RQ32.20-42-10-3/aab62:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7297)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8103)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

Moto G Power (2022)

### Additional information

The screen has rounded corners.

**Comment by Atemu** [comment]
What happens when you do the same in:

1. Regular NewPipe with the same settings as NewPipe Sponsorblock
2. A clean install of regular NewPipe
3. A clean install NewPipe Sponsorblock (wipe data, back up settings etc. first)

**Comment by VitoItalianGamer** [comment]
It happened on another device and might work the same.
