### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by WoAnerges** [polymorphicshade/NewPipe#353]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0252

### Steps to reproduce the bug

It randomly crashes during playback all the time

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference
	at org.schabi.newpipe.util.DeviceUtils.hasAnimationsAnimatorDurationEnabled(DeviceUtils.java:294)
	at org.schabi.newpipe.local.feed.FeedFragment.showNewItemsLoaded$lambda$22(FeedFragment.kt:601)
	at org.schabi.newpipe.local.feed.FeedFragment.$r8$lambda$PS5ueo6OP7FchkK75lIOG7kK1ck(FeedFragment.kt:0)
	at org.schabi.newpipe.local.feed.FeedFragment$$ExternalSyntheticLambda14.run(R8$$SyntheticClass:0)
	at org.schabi.newpipe.ktx.ExecOnEndListener.onAnimationEnd(View.kt:279)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1111)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1492)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1054)
	at android.view.Choreographer.doCallbacks(Choreographer.java:878)
	at android.view.Choreographer.doFrame(Choreographer.java:807)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:248)
	at android.app.ActivityThread.main(ActivityThread.java:7787)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

```
</details>
<hr>

### Affected Android/Custom ROM version

12

### Affected device model

Samsung

**Comment by Atemu** [comment]
How does upstream NewPipe behave with the same settings and user data?

**Comment by WoAnerges** [comment]
> How does upstream NewPipe behave with the same settings and user data?

I do not understand your question, it also crashes

**Comment by WoAnerges** [comment]
> How does upstream NewPipe behave with the same settings and user data?

It creates, too

**Comment by WoAnerges** [comment]
> How does upstream NewPipe behave with the same settings and user data?

It also crashes

**Comment by Atemu** [comment]
This issue has nothing to do with this fork then. Please read the template carefully, it's there for a reason.

**Comment by WoAnerges** [comment]
Sorry, I got confused with the downstream. !Correction: It doesn't crash upstream!
