### ISSUE TITLE
Getting random crashes/force quits when changing display modes

### ISSUE THREAD

**Issue by Akan9021** [polymorphicshade/NewPipe#45]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [X ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to any video
2. Flip the screen horizontally or vertically, it doesn't do it 100% of the time but it happens a fair amount.

### Actual behaviour
Crash to the home screen.

### Expected behavior
It adjusts the screen display to the given mode, either portrait or landscape.

This is a bug that I've encountered since the first release candidates all the way up to the recent 20.11 version, version 20.10 of both the fork and the original Newpipe don't have crashing issues.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.20.11
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.schabi.newpipe.util.VideoSegment[] org.schabi.newpipe.player.playqueue.PlayQueueItem.getVideoSegments()' on a null object reference
	at org.schabi.newpipe.player.Player.markSegments(Player.java:4292)
	at org.schabi.newpipe.player.Player.onPrepared(Player.java:2011)
	at org.schabi.newpipe.player.Player.onPlayerStateChanged(Player.java:1908)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$5(ExoPlayerImpl.java:828)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$5$ExoPlayerImpl$PlaybackInfoUpdate(Unknown Source:0)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$f6PAGX8HQVJ6dHmWeyT7ZcoD5DI.invokeListener(Unknown Source:2)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
	at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:826)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7707)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: OnePlus 8 5G

**Comment by polymorphicshade** [comment]
This should be fixed in the [latest release](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.20.11_r2).
