### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by yoge67855** [polymorphicshade/NewPipe#58]
time: 1619275316886
msg: java.lang.IllegalArgumentException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2569)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2631)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

stacktrace: java.lang.IllegalArgumentException: No such service ComponentInfo{org.polymorphicshade.newpipe/org.acra.sender.JobSenderService}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:308)
	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47)
	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.java:62)
	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.java:66)
	at org.acra.startup.StartupProcessorExecutor.lambda$null$0(StartupProcessorExecutor.java:86)
	at org.acra.startup.StartupProcessorExecutor.lambda$null$0$StartupProcessorExecutor(Unknown Source:0)
	at org.acra.startup.-$$Lambda$StartupProcessorExecutor$vr-B3Kby1WTBs7c-61N3dOEKizo.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2569)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2631)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

**Comment by Atemu** [comment]
Context?  
Steps to reproduce?  
Does the same happen on vanilla NewPipe?

**Comment by yoge67855** [comment]
Steps to reproduce:
Try to launch newpipe



Yes same thing is with vanilla kood

**Comment by Atemu** [comment]
Report it upstream then.

**Comment by polymorphicshade** [comment]
Closed as this issue does not seem specific to my fork.
