### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by ChunkyProgrammer** [polymorphicshade/NewPipe#60]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1) Open NewPipe
2) Tap "Play/Pause" button twice on Bluetooth speaker (without opening a video)
3) App crashes

### Actual behaviour
The app crashes

### Expected behavior
On Vanilla NewPipe, the app doesn't crash. 

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.2
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueue.getIndex()' on a null object reference
	at org.schabi.newpipe.player.Player.onCompleted(Player.java:2154)
	at org.schabi.newpipe.player.Player.changeState(Player.java:1993)
	at org.schabi.newpipe.player.Player.onPlayerStateChanged(Player.java:1913)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$13(ExoPlayerImpl.java:1052)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$eAKzukwdd6P91AoYEF8JC1HDnJ4.invoke(Unknown Source:4)
	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:297)
	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:184)
	at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6)
	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:205)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1101)
	at com.google.android.exoplayer2.ExoPlayerImpl.prepare(ExoPlayerImpl.java:333)
	at com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:1268)
	at com.google.android.exoplayer2.DefaultControlDispatcher.dispatchPrepare(DefaultControlDispatcher.java:57)
	at com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector$ComponentListener.onPlay(MediaSessionConnector.java:1156)
	at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onPlay(MediaSessionCompat.java:1614)
	at android.media.session.MediaSession$Callback.onMediaButtonEvent(MediaSession.java:928)
	at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onMediaButtonEvent(MediaSessionCompat.java:1604)
	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1566)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7867)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:11
 - Device model: LG Velvet 5

**Comment by ChunkyProgrammer** [comment]
Apparently the bug is in vanilla new pipe as well which makes sense considering the crash log didn't mention the localplayer file
