### ISSUE TITLE
app crashes when refreshed on wifi

### ISSUE THREAD

**Issue by Aadesh001** [polymorphicshade/NewPipe#72]
App tries to give captcha, whenever I try to refresh feed on wifi (2.4GHz) ( Non RSS, total subscription 192). shows two option, retry & solve. when clicked on solve, it gives this bug.
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ IN
* __Content Language:__ en-GB
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.21.5
* __OS:__ Linux Android 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: reasonPhrase can't be empty.
	at android.webkit.WebResourceResponse.setStatusCodeAndReasonPhrase(WebResourceResponse.java:138)
	at android.webkit.WebResourceResponse.<init>(WebResourceResponse.java:76)
	at xq.a(SourceFile:292)
	at alW.handleMessage(SourceFile:67)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:192)
	at android.app.ActivityThread.main(ActivityThread.java:6748)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:867)

```
</details>
<hr>

**Comment by Atemu** [comment]
Does the same happen with upstream NewPipe? This doesn't sound like anything that'd be different in our fork.

**Comment by Aadesh001** [comment]
Okay I installed the upstream Newpipe and tried to replicate the bug, it worked  perfectly. Once again tried to replicate bug in this version and it works well too now. Didn't understand what was the problem earlier.

**Comment by Atemu** [comment]
This sounds like an upstream bug in the feed fetcher when a captcha is required; maybe try it with something that is likely to require a captcha like a VPN proxy or TOR.

**Comment by Aadesh001** [comment]
I cannot replicate the problem anymore, neither in this version, nor in upstream :(

**Comment by polymorphicshade** [comment]
Closed as it looks like this is not repeatable.
